import Head from "next/head";
import { Inter } from "@next/font/google";

//Components
import Footer from "../components/footer/Footer";
import Hero from "../components/HeroSection/Hero";
import Nav from "../components/Nav/Nav";


import { LinkingModel } from "../components/model/LinkModel";
import { CardModel } from "../components/model/CardModel";
import CardPage from "../components/Cards/Cards";

const Links: LinkingModel[] = [
  new LinkingModel("1", "cases", "#cases"),
  new LinkingModel("2", "priser", "#blabla"),
];

const InfoCard: CardModel[] = [
  new CardModel(5, "test", "lorem ibsum", "her er ekstra"),
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Veveve</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav links={Links} />
      <Hero title="jeg er ikke google premium partner, fordi jeg ikke arbejder for google jeg arbejder for jer" />
      <CardPage cardData={data} />

      <Footer />
    </>
  );
}

