import Head from "next/head";
import { Inter } from "@next/font/google";
import { GetStaticProps } from "next";
//Components
import Footer from "../components/footer/Footer";
import Hero from "../components/HeroSection/Hero";
import Nav from "../components/Nav/Nav";

import { LinkingModel } from "../components/model/LinkModel";
import MyComponent from "../components/Cards/Test";

const Links: LinkingModel[] = [
  new LinkingModel("1", "cases", "#cases"),
  new LinkingModel("2", "priser", "#blabla"),
];

interface Props {
  data: any;
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const data = await fetch("http://localhost:3000/api/hello")
    .then((res) => res.json())
    .catch((err) => console.error(err));

  return {
    props: {
      data,
    },
  };
};

export default function Home({ data }: Props) {
  return (
    <>
      <Head>
        <title>Veveve</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav links={Links} />
      <Hero title="" />

      <MyComponent data={data} />

      <Footer />
    </>
  );
}
